site_name: discord.ext.wizard
site_description: A discord.py extension for setting-up wizards

site_name: discord-ext-wizard
site_author: FalseDev

repo_name: discord-ext-wizard
repo_url: https://github.com/FalseDev/discord-ext-wizard

docs_dir: docs

theme:
  name: material
  language: en
  palette:
    - scheme: slate
      primary: indigo
      accent: white
  features:
  - search.suggest
  - search.highlight

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences


plugins:
  - search
  - mkdocstrings:
      handler: python

nav:
  - Introduction: index.md